### ISSUE TITLE
Wrong config.php location

### ISSUE THREAD

**Issue by kamillos** [TobyMaxham/ux9-api#4]
Please don't place the config.php in venodor.

**Comment by TobyMaxham** [comment]
Thanks for that. I think I'll remove it. If you will use the package for Laravel reasons I will add the config there

**Comment by TobyMaxham** [comment]
I have change config handling: https://github.com/TobyMaxham/ux9-api/commit/f314671618a1244008d549d8d7c36bf543a72a03
